pipeline {

  agent any

  tools {
    nodejs 'node-14.17.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    
    stage('Install dependencies') {
      steps {
        sh 'cd React && npm i'
      }
    }
    stage('Build project') {
      steps {
        sh 'cd React && npm run build'
      }
    }

    stage('Clone the github pages project') {
      steps {
        sh 'git clone https://github.com/FranciscoCasales/FranciscoCasales.github.io.git'
        sh 'cd FranciscoCasales'
      }
    }
  }
}